CMAKE_MINIMUM_REQUIRED(VERSION 3.0.2)

MACRO(CONCRETE_C_CONFIG_OPTION_ENABLE)
    CMAKE_PARSE_ARGUMENTS(
        CONCRETE
        ""
        "WIN32_SHUT_MIN_MAX;"
        ""
        ${ARGN}
    )

    _CONCRETE_APPEND_CONFIG_OPTION(${CONCRETE_WIN32_SHUT_MIN_MAX} -DCONCRETE_WIN32_SHUT_MIN_MAX)
ENDMACRO(CONCRETE_C_CONFIG_OPTION_ENABLE)

MACRO(CONCRETE_GEN_C_CONFIG_FILE DEST_PATH)
    _CONCRETE_GEN_CONFIG_FILE(C_CONFIG.h.in ${DEST_PATH})
ENDMACRO(CONCRETE_GEN_C_CONFIG_FILE)