CMAKE_MINIMUM_REQUIRED(VERSION 3.0.2)

MACRO(CONCRETE_C_CXX_CONFIG_OPTION_ENABLE)
    CMAKE_PARSE_ARGUMENTS(
        CONCRETE
        ""
        "WIN32_SHUT_MIN_MAX;CXX_USE_BOOST;CXX_USE_BOOST_ALL_DYN_LINK"
        ""
        ${ARGN}
    )

    _CONCRETE_APPEND_CONFIG_OPTION(${CONCRETE_WIN32_SHUT_MIN_MAX} -DCONCRETE_WIN32_SHUT_MIN_MAX)

    _CONCRETE_APPEND_CONFIG_OPTION(${CONCRETE_CXX_USE_BOOST} -DCONCRETE_USE_BOOST)

    _CONCRETE_APPEND_CONFIG_OPTION(${CONCRETE_CXX_USE_BOOST_ALL_DYN_LINK} -DCONCRETE_USE_BOOST_ALL_DYN_LINK)
ENDMACRO(CONCRETE_C_CXX_CONFIG_OPTION_ENABLE)

MACRO(CONCRETE_GEN_C_CXX_CONFIG_FILE DEST_PATH)
    _CONCRETE_GEN_CONFIG_FILE(C_CXX_CONFIG.h.in ${DEST_PATH})
ENDMACRO(CONCRETE_GEN_C_CXX_CONFIG_FILE)
