CMAKE_MINIMUM_REQUIRED(VERSION 3.0.2)

MACRO(CONCRETE_C_CXX_CONFIG_OPTION_ENABLE)

    SET(_WIN32_PREPROCESS_FLAGS "WIN32_SHUT_MIN_MAX;WIN32_CRT_SECURE_NO_DEPRECATE;WIN32_SCL_SECURE_NO_DEPRECATE;")
    SET(_C_PREPROCESS_FLAGS "C_USE_C99_BOOL_TYPE;")
    SET(_CXX_PREPROCESS_FLAGS "CXX_USE_BOOST;CXX_USE_BOOST_ALL_DYN_LINK;")

    CMAKE_PARSE_ARGUMENTS(
        CONCRETE
        ""
        "${_WIN32_PREPROCESS_FLAGS}${_C_PREPROCESS_FLAGS}${_CXX_PREPROCESS_FLAGS}"
        ""
        ${ARGN}
    )

    if (MSVC)
        _CONCRETE_APPEND_CONFIG_OPTION(${CONCRETE_WIN32_SHUT_MIN_MAX} -DCONCRETE_WIN32_SHUT_MIN_MAX)
        _CONCRETE_APPEND_CONFIG_OPTION(${CONCRETE_WIN32_CRT_SECURE_NO_DEPRECATE} -DCONCRETE_WIN32_CRT_SECURE_NO_DEPRECATE)
        _CONCRETE_APPEND_CONFIG_OPTION(${CONCRETE_WIN32_SCL_SECURE_NO_DEPRECATE} -DCONCRETE_WIN32_SCL_SECURE_NO_DEPRECATE)
    endif()

    _CONCRETE_APPEND_CONFIG_OPTION(${CONCRETE_CXX_USE_BOOST} -DCONCRETE_USE_BOOST)

    _CONCRETE_APPEND_CONFIG_OPTION(${CONCRETE_CXX_USE_BOOST_ALL_DYN_LINK} -DCONCRETE_USE_BOOST_ALL_DYN_LINK)

    _CONCRETE_APPEND_CONFIG_OPTION(${CONCRETE_C_USE_C99_BOOL_TYPE} -DCONCRETE_USE_C99_BOOL_TYPE)

ENDMACRO(CONCRETE_C_CXX_CONFIG_OPTION_ENABLE)

MACRO(CONCRETE_GEN_C_CXX_CONFIG_FILE DEST_PATH)
    _CONCRETE_GEN_CONFIG_FILE(C_CXX_CONFIG.h.in ${DEST_PATH})
ENDMACRO(CONCRETE_GEN_C_CXX_CONFIG_FILE)
