CMAKE_MINIMUM_REQUIRED(VERSION 3.0.2)

SET(CONCRETE_BASE_DEFINITIONS)

# Config Option
SET(CONCRETE_WIN32_SHUT_MIN_MAX FALSE CACHE BOOL "Shut win32 min/max" FORCE)

# CXX
SET(CONCRETE_CXX_USE_BOOST FALSE CACHE BOOL "Is use boost library" FORCE)
SET(CONCRETE_CXX_USE_BOOST_ALL_DYN_LINK FALSE CACHE BOOL "Boost all link dynamic library" FORCE)

MACRO(_CONCRETE_GEN_CONFIG_FILE CONFIG_FILE DEST_PATH)
    IF (NOT ${CONCRETE_INIT_COMPLETED})
        MESSAGE(FATAL_ERROR "Library has not been initialized! please call concrete_init first!")
    ENDIF()

    CONFIGURE_FILE(
        ${CONCRETE_PATH}/${CONFIG_FILE}
        ${DEST_PATH}
    )
ENDMACRO(_CONCRETE_GEN_CONFIG_FILE)

MACRO(_CONCRETE_APPEND_CONFIG_OPTION OPTION MACRO)
    IF(${OPTION})
        LIST(APPEND CONCRETE_BASE_DEFINITIONS ${MACRO})
    ENDIF()
ENDMACRO(_CONCRETE_APPEND_CONFIG_OPTION)