CMAKE_MINIMUM_REQUIRED(VERSION 3.0.2)

FUNCTION (CONCRETE_UTEST_STR_EQUAL LHS RHS)
    IF (${LHS} STREQUAL ${RHS})
        MESSAGE(STATUS "${LHS} == ${RHS} -- TEST OK")
    ELSE()
        MESSAGE(FATAL_ERROR "${LHS} == ${RHS} -- TEST ERROR")
    ENDIF()
ENDFUNCTION(CONCRETE_UTEST_STR_EQUAL)