# MIT License
# 
# Copyright (c) 2019 MadStrawberry
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
# 
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
# 
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

INCLUDE_GUARD(GLOBAL)

# CMake standard module
INCLUDE( CMakeParseArguments )

FUNCTION(CONCRETE_INTERNAL_METHOD_SYSTEM_INFO_QUEARY_AND_SET KEY VARIABLE)
    CMAKE_HOST_SYSTEM_INFORMATION(RESULT result QUERY ${KEY})
    SET_PROPERTY(CACHE ${VARIABLE} PROPERTY VALUE ${result})
ENDFUNCTION(CONCRETE_INTERNAL_METHOD_SYSTEM_INFO_QUEARY_AND_SET)

FUNCTION(CONCRETE_METHOD_COLLECT_SYSTEM_INFORMATION)
    # Query logical cpu core number
    CONCRETE_INTERNAL_METHOD_SYSTEM_INFO_QUEARY_AND_SET(NUMBER_OF_LOGICAL_CORES CONCRETE_ENVIONMENT_SYSTEM_INFO_NUMBER_OF_LOGICAL_CORES)

    CONCRETE_INTERNAL_METHOD_SYSTEM_INFO_QUEARY_AND_SET(NUMBER_OF_PHYSICAL_CORES CONCRETE_ENVIONMENT_SYSTEM_INFO_NUMBER_OF_PHYSICAL_CORES)

    CONCRETE_INTERNAL_METHOD_SYSTEM_INFO_QUEARY_AND_SET(HOSTNAME CONCRETE_ENVIONMENT_SYSTEM_INFO_HOSTNAME)

    CONCRETE_INTERNAL_METHOD_SYSTEM_INFO_QUEARY_AND_SET(FQDN CONCRETE_ENVIONMENT_SYSTEM_INFO_FQDN)

    CONCRETE_INTERNAL_METHOD_SYSTEM_INFO_QUEARY_AND_SET(TOTAL_VIRTUAL_MEMORY CONCRETE_ENVIONMENT_SYSTEM_INFO_TOTAL_VIRTUAL_MEMORY)

    CONCRETE_INTERNAL_METHOD_SYSTEM_INFO_QUEARY_AND_SET(AVAILABLE_VIRTUAL_MEMORY CONCRETE_ENVIONMENT_SYSTEM_INFO_AVAILABLE_VIRTUAL_MEMORY)

    CONCRETE_INTERNAL_METHOD_SYSTEM_INFO_QUEARY_AND_SET(TOTAL_PHYSICAL_MEMORY CONCRETE_ENVIONMENT_SYSTEM_INFO_TOTAL_PHYSICAL_MEMORY)

    CONCRETE_INTERNAL_METHOD_SYSTEM_INFO_QUEARY_AND_SET(AVAILABLE_PHYSICAL_MEMORY CONCRETE_ENVIONMENT_SYSTEM_INFO_AVAILABLE_PHYSICAL_MEMORY)

    CONCRETE_INTERNAL_METHOD_SYSTEM_INFO_QUEARY_AND_SET(IS_64BIT CONCRETE_ENVIONMENT_SYSTEM_INFO_IS_64BIT)

    CONCRETE_INTERNAL_METHOD_SYSTEM_INFO_QUEARY_AND_SET(HAS_FPU CONCRETE_ENVIONMENT_SYSTEM_INFO_HAS_FPU)

    CONCRETE_INTERNAL_METHOD_SYSTEM_INFO_QUEARY_AND_SET(HAS_MMX CONCRETE_ENVIONMENT_SYSTEM_INFO_HAS_MMX)

    CONCRETE_INTERNAL_METHOD_SYSTEM_INFO_QUEARY_AND_SET(HAS_MMX_PLUS CONCRETE_ENVIONMENT_SYSTEM_INFO_HAS_MMX_PLUS)

    CONCRETE_INTERNAL_METHOD_SYSTEM_INFO_QUEARY_AND_SET(HAS_SSE CONCRETE_ENVIONMENT_SYSTEM_INFO_HAS_SSE)

    CONCRETE_INTERNAL_METHOD_SYSTEM_INFO_QUEARY_AND_SET(HAS_SSE2 CONCRETE_ENVIONMENT_SYSTEM_INFO_HAS_SSE2)

    CONCRETE_INTERNAL_METHOD_SYSTEM_INFO_QUEARY_AND_SET(HAS_SSE_FP CONCRETE_ENVIONMENT_SYSTEM_INFO_HAS_SSE_FP)

    CONCRETE_INTERNAL_METHOD_SYSTEM_INFO_QUEARY_AND_SET(HAS_SSE_MMX CONCRETE_ENVIONMENT_SYSTEM_INFO_HAS_SSE_MMX)

    CONCRETE_INTERNAL_METHOD_SYSTEM_INFO_QUEARY_AND_SET(HAS_AMD_3DNOW CONCRETE_ENVIONMENT_SYSTEM_INFO_HAS_AMD_3DNOW)

    CONCRETE_INTERNAL_METHOD_SYSTEM_INFO_QUEARY_AND_SET(HAS_AMD_3DNOW_PLUS CONCRETE_ENVIONMENT_SYSTEM_INFO_HAS_AMD_3DNOW_PLUS)

    CONCRETE_INTERNAL_METHOD_SYSTEM_INFO_QUEARY_AND_SET(HAS_IA64 CONCRETE_ENVIONMENT_SYSTEM_INFO_HAS_IA64)

    CONCRETE_INTERNAL_METHOD_SYSTEM_INFO_QUEARY_AND_SET(HAS_SERIAL_NUMBER CONCRETE_ENVIONMENT_SYSTEM_INFO_HAS_SERIAL_NUMBER)

    CONCRETE_INTERNAL_METHOD_SYSTEM_INFO_QUEARY_AND_SET(PROCESSOR_SERIAL_NUMBER CONCRETE_ENVIONMENT_SYSTEM_INFO_PROCESSOR_SERIAL_NUMBER)

    CONCRETE_INTERNAL_METHOD_SYSTEM_INFO_QUEARY_AND_SET(PROCESSOR_NAME CONCRETE_ENVIONMENT_SYSTEM_INFO_PROCESSOR_NAME)

    CONCRETE_INTERNAL_METHOD_SYSTEM_INFO_QUEARY_AND_SET(PROCESSOR_DESCRIPTION CONCRETE_ENVIONMENT_SYSTEM_INFO_PROCESSOR_DESCRIPTION)

    CONCRETE_INTERNAL_METHOD_SYSTEM_INFO_QUEARY_AND_SET(OS_NAME CONCRETE_ENVIONMENT_SYSTEM_INFO_OS_NAME)

    CONCRETE_INTERNAL_METHOD_SYSTEM_INFO_QUEARY_AND_SET(OS_RELEASE CONCRETE_ENVIONMENT_SYSTEM_INFO_OS_RELEASE)

    CONCRETE_INTERNAL_METHOD_SYSTEM_INFO_QUEARY_AND_SET(OS_VERSION CONCRETE_ENVIONMENT_SYSTEM_INFO_OS_VERSION)

    CONCRETE_INTERNAL_METHOD_SYSTEM_INFO_QUEARY_AND_SET(OS_PLATFORM CONCRETE_ENVIONMENT_SYSTEM_INFO_OS_PLATFORM)
ENDFUNCTION(CONCRETE_METHOD_COLLECT_SYSTEM_INFORMATION)

FUNCTION(CONCRETE_METHOD_PRINT_SYSTEM_INFORMATION)

ENDFUNCTION(CONCRETE_METHOD_PRINT_SYSTEM_INFORMATION)